# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 00:46
from __future__ import unicode_literals

import aboutconfig.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=512, validators=[django.core.validators.RegexValidator('(\\w\\.)*\\w')])),
                ('value', models.CharField(blank=True, null=True, max_length=1024)),
                ('default_value', models.CharField(editable=False, max_length=1024)),
                ('allow_template_use', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('serializer_class', models.CharField(max_length=256, validators=[aboutconfig.utils.serializer_validator])),
            ],
        ),
        migrations.AddField(
            model_name='config',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aboutconfig.DataType'),
        ),
    ]
